import Head from 'next/head'
import Image from 'next/image'

const Home = () => {
  return (
    <div>
      <Head>
        <title>L&H Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}

export default Home